# Site settings
title: Aleksander Grzyb
email: aleksander.grzyb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! This is Aleksander's blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aleksandergrzyb.github.io" # the base hostname & protocol for your site
twitter_username: aleksandergrzyb
github_username:  aleksandergrzyb

# Build settings
markdown: kramdown
exclude: ["CNAME", "Rakefile", "Gemfile", "Gemfile.lock"]
